version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: Microsoft.Extensions.TimeProvider.Testing
        update-types:
          - version-update:semver-major
      - dependency-name: Verify.XunitV3
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      codeql-version-updates:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
      codeql-security-updates:
        applies-to: security-updates
        patterns:
          - "github/codeql-action/*"
