<Project>
  <PropertyGroup Condition="'$(IsPackable)' == 'true'">
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion Condition="'$(SkipPackageValidationBaseline)' != 'true'">1.0.5</PackageValidationBaselineVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
