<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XBullet.EasyTesting\XBullet.EasyTesting.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.EntityFrameworkCore\XBullet.EasyTesting.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Http\XBullet.EasyTesting.Http.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Messaging\XBullet.EasyTesting.Messaging.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Snapshots\XBullet.EasyTesting.Snapshots.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Verify.Xunit\XBullet.EasyTesting.Verify.Xunit.csproj" />
    <ProjectReference Include="..\TestApi\TestApi.csproj" />
  </ItemGroup>
</Project>
