<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XBullet.EasyTesting\XBullet.EasyTesting.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Aspire\XBullet.EasyTesting.Aspire.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.EntityFrameworkCore\XBullet.EasyTesting.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Http\XBullet.EasyTesting.Http.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Messaging\XBullet.EasyTesting.Messaging.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Observability\XBullet.EasyTesting.Observability.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Testcontainers\XBullet.EasyTesting.Testcontainers.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Snapshots\XBullet.EasyTesting.Snapshots.Core.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Verify.Xunit\XBullet.EasyTesting.Verify.Xunit.csproj" />
    <ProjectReference Include="..\TestApi\TestApi.csproj" />
    <ProjectReference Include="..\TestAppHost\TestAppHost.csproj"
                      Condition="'$(TargetFramework)' == 'net10.0'"
                      IsAspireProjectResource="false"
                      Aliases="testapphost" />
  </ItemGroup>
</Project>
