<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Azure\XBullet.EasyTesting.Azure.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Messaging\XBullet.EasyTesting.Messaging.csproj" />
    <ProjectReference Include="..\..\src\XBullet.EasyTesting.Snapshots.Compatibility\XBullet.EasyTesting.Snapshots.Compatibility.csproj" />
  </ItemGroup>
</Project>
